### ISSUE TITLE
能否在侧边栏实现二级菜单？

### ISSUE THREAD

**Issue by ghostist** [shaonianzhentan/ha_sidebar#1]
如题，一些设置类的、管理类的统一放在二级
尤其在手机端，侧边栏一多还需要上下滑动....加入二级菜单应该会比较清爽

**Comment by shaonianzhentan** [comment]
你可以使用这个，一个web桌面，集中式管理比较合适
https://github.com/shaonianzhentan/ha_ylui

**Comment by shadowby** [comment]
> 你可以使用这个，一个web桌面，集中式管理比较合适
> https://github.com/shaonianzhentan/ha_ylui

大佬,这个web桌面如何管理ha里的插件?或者如何把ha里想作为二级菜单的添加的web桌面上?
