### ISSUE TITLE
2.1版本只有新建，没有看见管理功能？

### ISSUE THREAD

**Issue by jacksky6** [shaonianzhentan/ha_sidebar#10]
2.1版本只有新建，没有看见管理功能

**Comment by jacksky6** [comment]
v2.0（不兼容1.x版本）
删除隐藏默认菜单功能

原来如此

**Comment by shaonianzhentan** [comment]
### 长按HomeAssistant进入编辑模式，这是HA内置的功能
![image](https://user-images.githubusercontent.com/5294022/132150691-fd8b5278-7768-4727-8c29-ac5ffc7065af.png)
