### ISSUE TITLE
长链接有问题，还是带参数的链接有问题？

### ISSUE THREAD

**Issue by cctv838126** [shaonianzhentan/ha_sidebar#3]
https://open.ys7.com/ezopen/h5/iframe_se?url=ezopen://open.ys7.com/XXXXXX/1.hd.live&autoplay=1&audio=1&accessToken=XXXXXX，
这样的链接加上去后，打开变成了
https://open.ys7.com/ezopen/h5/iframe_se?url=ezopen://open.ys7.com/XXXXXX/1.hd.live
后边的参数都没有，导致无法访问
貌似二级菜单里正常，侧边栏就不行

**Comment by shaonianzhentan** [comment]
> [https://open.ys7.com/ezopen/h5/iframe_se?url=ezopen://open.ys7.com/XXXXXX/1.hd.live&autoplay=1&audio=1&accessToken=XXXXXX，](https://open.ys7.com/ezopen/h5/iframe_se?url=ezopen://open.ys7.com/XXXXXX/1.hd.live&autoplay=1&audio=1&accessToken=XXXXXX%EF%BC%8C)
> 这样的链接加上去后，打开变成了
> https://open.ys7.com/ezopen/h5/iframe_se?url=ezopen://open.ys7.com/XXXXXX/1.hd.live
> 后边的参数都没有，导致无法访问
> 貌似二级菜单里正常，侧边栏就不行

1.4版本已经解决了这个问题
