### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GWan1234** [shaonianzhentan/ha_sidebar#5]
感谢你的项目，很棒，我通过它在HA添加了HB、NR等侧栏，但是有一个小bug，

选择隐藏HA自带的地图、日志之后，换浏览器或者是刷新浏览器会自己打开地图、日志，

官方可以隐藏，但是关闭默认配置会一起关闭太多东西，手动启用附属关闭的功能也会更麻烦，

烦请大佬优化一下，十分感谢。

环境：电脑-Edge浏览器
       ：手机-Safari浏览器&Edge浏览器

**Comment by shaonianzhentan** [comment]
这不是一个BUG，设计就是如此，开关默认侧栏菜单只在当前浏览器有效

**Comment by GWan1234** [comment]
原来这样啊，好的，谢谢回复。
