### ISSUE TITLE
https 无法跳转到http

### ISSUE THREAD

**Issue by hyf635269547** [shaonianzhentan/ha_sidebar#6]
ha 地址https://xxxx.com   如果添加的菜单为http时 无法直接跳转

**Comment by hyf635269547** [comment]
Mixed Content: The page at 'https://xxxx.com/_1590661908.683409' was loaded over HTTPS, but requested an insecure frame 'http://10.115.50.2:8086/'. This request has been blocked; the content must be served over HTTPS.

**Comment by shaonianzhentan** [comment]
这个是浏览器的限制，你可以点击浏览器输入地址栏右边的`允许不安全的链接`操作
