### ISSUE TITLE
homeassistant更新到最新版后，会提示配置错误

### ISSUE THREAD

**Issue by ycg31** [shaonianzhentan/ha_sidebar#8]
core-2021.6.6
supervisor-2021.06.6
Home Assistant OS 6.1

ha_sidebar是最新版的2.0.2 ，配置文件加入ha_sidebar，检查配置时就会提示错误
Component error: ha_sidebar - Integration 'ha_sidebar' not found.

**Comment by shaonianzhentan** [comment]
请将组件更新到最新版
